### ISSUE TITLE
Failing to Enter World due to and error in JsonObject

### ISSUE THREAD

**Issue by quiqueck** [Additional-Mods/additionaladditions#59]
When entering a World, I get the following error with Version 3.0.1 in Minecraft 1.18.1:

```
[11:02:22] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: JsonObject
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.class_310.method_29604(class_310.java:2155) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_29610(class_310.java:2003) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.handler$zjp000$bclib_callFixerOnLoad(class_310.java:5033) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_29606(class_310.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:436) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:342) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:273) ~[client-intermediary.jar:?]
	at net.minecraft.class_350.method_25402(class_350.java:359) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:491) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:165) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:195) [client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:310) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1142) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
Caused by: java.lang.UnsupportedOperationException: JsonObject
	at com.google.gson.JsonElement.getAsBoolean(JsonElement.java:153) ~[gson-2.8.8.jar:?]
	at dqu.additionaladditions.config.Config.get(Config.java:94) ~[AdditionalAdditions-3.0.1.jar:?]
	at net.minecraft.class_1863.handler$zzh000$removeRecipes(class_1863.java:1037) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_29604(class_310.java:2154) ~[client-intermediary.jar:?]
	... 29 more

**Comment by Dqu1J** [comment]
Try resetting your config file (additional-additions-config.json). If nothing helps, update to 1.18.2 and ADAD 4.0.3. We don’t support old versions.

**Comment by quiqueck** [comment]
Reseting the config did the trick. 

Thanks for the quick help. Very much appreciated. :)
