### ISSUE TITLE
incompatible with friends and foes

### ISSUE THREAD

**Issue by Ur3rdIMcFly** [Additional-Mods/additionaladditions#69]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 6/12/22, 12:45 PM
Description: Starting integrated server

java.lang.NoSuchMethodError: 'net.minecraft.class_2960 dev.architectury.registry.level.biome.BiomeModifications$BiomeContext.getKey()'
	at com.faboslav.friendsandfoes.init.ModEntityTypes.lambda$initBiomeModifications$6(ModEntityTypes.java:81)
	at dev.architectury.registry.level.biome.fabric.BiomeModificationsImpl.lambda$registerModification$0(BiomeModificationsImpl.java:93)
	at net.fabricmc.fabric.impl.biome.modification.BiomeModificationImpl$ModifierRecord.apply(BiomeModificationImpl.java:208)
	at net.fabricmc.fabric.impl.biome.modification.BiomeModificationImpl.finalizeWorldGen(BiomeModificationImpl.java:150)
	at net.minecraft.server.MinecraftServer.handler$zka000$finalizeWorldGen(MinecraftServer.java:2289)
	at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:296)
	at net.minecraft.class_1132.<init>(class_1132.java:49)
	at net.minecraft.class_310.method_29603(class_310.java:2005)
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:265)
	at net.minecraft.class_310.method_29610(class_310.java:2005)
	at net.minecraft.class_7196.method_41889(class_7196.java:100)
	at net.minecraft.class_525.method_41847(class_525.java:326)
	at net.minecraft.class_7196.method_41892(class_7196.java:247)
	at net.minecraft.class_525.method_2736(class_525.java:310)
	at net.minecraft.class_525.method_19922(class_525.java:260)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.faboslav.friendsandfoes.init.ModEntityTypes.lambda$initBiomeModifications$6(ModEntityTypes.java:81)
	at dev.architectury.registry.level.biome.fabric.BiomeModificationsImpl.lambda$registerModification$0(BiomeModificationsImpl.java:93)
	at net.fabricmc.fabric.impl.biome.modification.BiomeModificationImpl$ModifierRecord.apply(BiomeModificationImpl.java:208)
	at net.fabricmc.fabric.impl.biome.modification.BiomeModificationImpl.finalizeWorldGen(BiomeModificationImpl.java:150)
	at net.minecraft.server.MinecraftServer.handler$zka000$finalizeWorldGen(MinecraftServer.java:2289)
	at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:296)
	at net.minecraft.class_1132.<init>(class_1132.java:49)
	at net.minecraft.class_310.method_29603(class_310.java:2005)
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:265)
	at net.minecraft.class_310.method_29610(class_310.java:2005)
	at net.minecraft.class_7196.method_41889(class_7196.java:100)
	at net.minecraft.class_525.method_41847(class_525.java:326)
	at net.minecraft.class_7196.method_41892(class_7196.java:247)
	at net.minecraft.class_525.method_2736(class_525.java:310)
	at net.minecraft.class_525.method_19922(class_525.java:260)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)

-- Starting integrated server --
Details:
	Level ID: New World (3)
	Level Name: New World
Stacktrace:
	at net.minecraft.class_310.method_29610(class_310.java:2005)
	at net.minecraft.class_7196.method_41889(class_7196.java:100)
	at net.minecraft.class_525.method_41847(class_525.java:326)
	at net.minecraft.class_7196.method_41892(class_7196.java:247)
	at net.minecraft.class_525.method_2736(class_525.java:310)
	at net.minecraft.class_525.method_19922(class_525.java:260)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_525
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, illuminations/pixelaccurate
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2295)
	at net.minecraft.class_310.method_1514(class_310.java:753)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2491981520 bytes (2376 MiB) / 4483710976 bytes (4276 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: unknown
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Virtual Desktop Monitor
	Graphics card #0 vendor: Virtual Desktop, Inc.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=9.7.20.44
	Graphics card #1 name: NVIDIA GeForce RTX 2080
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1e87
	Graphics card #1 versionInfo: DriverVersion=30.0.15.1277
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.60
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.60
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 35859.38
	Virtual memory used (MB): 16116.98
	Swap memory total (MB): 3200.00
	Swap memory used (MB): 0.00
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx8192m
	Fabric Mods: 
		additionaladditions: Additional Additions 5.0.0
		advancementscreenshot-fabric: Advancement Screenshot (Fabric) 3.3
		ambientenvironment: Ambient Environment 8.0+1
		appleskin: AppleSkin 2.4.0+mc1.19
		architectury: Architectury 5.6.22
		axesareweapons: Axes Are Weapons 1.5.2
		axolotlitemfix: Axolotl Item Fix 1.1.3
		badpackets: Bad Packets 0.1.2
		betterf3: BetterF3 1.3.1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.3+9e7660c6a9
		betterthirdperson: Better Third Person 1.8.0
		bookshelf: Bookshelf 14.0.2
		capybara: Capybara 1.0.4
		chisel: Chisel Refabricated 1.4.6
		cloth-config: Cloth Config v6 7.0.69
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+1
		collective-fabric: Collective (Fabric) 4.27
			fiber: fiber 0.23.0-2
		couplings: Couplings 1.9.0+1.19
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
		dynamicsoundfilters: Dynamic Sound Filters 1.3.0+1.19
		effective: Effective 1.2.2
		enchdesc: EnchantmentDescriptions 11.0.2
		fabric: Fabric API 0.55.3+1.19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.6+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.12+e62f51a3a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.5+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.1+cda9839ba9
			fabric-commands-v0: Fabric Commands (v0) 0.2.22+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.16+9ff28f40a9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.0.1+2a5b9210a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.27+72da3b3da9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.24+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.23+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.9+21a5acaaa9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.0.1+9e7660c6a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.1+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.7+9ff28f40a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.5+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.16+92cf9a3ea9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.6+9ff28f40a9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.23+9ff28f40a9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.8+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.0+kotlin.1.7.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.17.3
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.7
		fallingleaves: Falling Leaves 1.12.1+1.19
		friendsandfoes: Friends&Foes 1.5.0
			mm: Manningham Mills 2.3
		geckolib3: Geckolib 3.1.2
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		illuminations: Illuminations 1.10.5
		inventoryhud: Inventory HUD + 3.4.2
		inventoryprofilesnext: Inventory Profiles Next 1.5.1
		java: Java HotSpot(TM) 64-Bit Server VM 17
		mavm: More Axolotl Variants Mod 1.0.8a
		minecraft: Minecraft 1.19
		mo_glass: Mo Glass 1.6.1-MC1.19
		modid: Creatures Of The Snow 2.2.0+1.19
		modmenu: Mod Menu 4.0.0
		respawnablepets: Respawnable Pets 1.19-1
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.0-beta.1
			midnightlib: MidnightLib 0.5.1
		roughlyenoughitems: Roughly Enough Items 9.0.475
		shulkerboxtooltip: Shulker Box Tooltip 3.0.9-beta.1+1.19-rc2
		skinlayers: 3d Skin Layers 1.4.7-mc1.19
		wthit: wthit 5.1.4
		xaerominimap: Xaero's Minimap 22.9.2
		xaeroworldmap: Xaero's World Map 1.23.2
	Launched Version: 1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 2080/PCIe/SSE2 GL version 3.2.0 NVIDIA 512.77, NVIDIA Corporation
	Window size: 3440x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, illuminations/pixelaccurate
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz

**Comment by Dqu1J** [comment]
Are you sure?
